// =============================================================================
// CivicConnect TN — Historical Civic Complaints Dataset (Seed for Data Mining)
// =============================================================================
// Rich, geographically accurate dataset of 80+ civic complaints covering
// high-density geographic clusters and rural noise outliers across Tamil Nadu.

import { DataPoint } from './types';

export const HISTORICAL_MINING_DATASET: DataPoint[] = [
  // ===========================================================================
  // CLUSTER 1: Chennai T. Nagar — Potholes & Road Infrastructure (Ward 114)
  // Centroid: ~13.0418, 80.2341
  // ===========================================================================
  {
    id: 'dmt-tn-01',
    tracking_id: 'CC-TN-2026-104921',
    title: 'Severe Pothole Cluster on Usman Road Flyover descent',
    description: 'Multiple deep potholes covering 15 meters on the descent towards T. Nagar bus terminus.',
    category_id: 'ROADS_POTHOLE',
    category_name: 'Pothole',
    department_id: 'd0000001-0000-0000-0000-000000000002',
    department_name: 'Roads & Infrastructure',
    status: 'in_progress',
    priority: 'high',
    address: 'Usman Road Flyover, T. Nagar, Chennai',
    ward: 114,
    district: 'Chennai',
    latitude: 13.0418,
    longitude: 80.2341,
    created_at: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 42,
  },
  {
    id: 'dmt-tn-02',
    tracking_id: 'CC-TN-2026-104925',
    title: 'Caved in road trench near Ranganathan Street corner',
    description: 'Uncovered trench dug for optical cable left open, vehicles getting stuck.',
    category_id: 'ROADS_DAMAGE',
    category_name: 'Road Damage',
    department_id: 'd0000001-0000-0000-0000-000000000002',
    department_name: 'Roads & Infrastructure',
    status: 'created',
    priority: 'urgent',
    address: 'Near Ranganathan St, South Usman Road, T. Nagar',
    ward: 114,
    district: 'Chennai',
    latitude: 13.0409,
    longitude: 80.2335,
    created_at: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 38,
  },
  {
    id: 'dmt-tn-03',
    tracking_id: 'CC-TN-2026-104930',
    title: 'Tar layer eroded on Panagal Park roundabout',
    description: 'Entire top asphalt layer washed away exposing sharp gravel stones.',
    category_id: 'ROADS_POTHOLE',
    category_name: 'Pothole',
    department_id: 'd0000001-0000-0000-0000-000000000002',
    department_name: 'Roads & Infrastructure',
    status: 'assigned',
    priority: 'high',
    address: 'Panagal Park Roundabout, T. Nagar, Chennai',
    ward: 114,
    district: 'Chennai',
    latitude: 13.0425,
    longitude: 80.2352,
    created_at: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 29,
  },
  {
    id: 'dmt-tn-04',
    tracking_id: 'CC-TN-2026-104934',
    title: 'Large crater near Saravana Stores crossing',
    description: 'Waterlogged crater after light rain causing 2-wheeler skidding.',
    category_id: 'ROADS_POTHOLE',
    category_name: 'Pothole',
    department_id: 'd0000001-0000-0000-0000-000000000002',
    department_name: 'Roads & Infrastructure',
    status: 'in_progress',
    priority: 'urgent',
    address: 'North Usman Road, near Saravana Stores, T. Nagar',
    ward: 114,
    district: 'Chennai',
    latitude: 13.0432,
    longitude: 80.2348,
    created_at: new Date(Date.now() - 6 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 51,
  },
  {
    id: 'dmt-tn-05',
    tracking_id: 'CC-TN-2026-104940',
    title: 'Footpath pavers collapsed into storm drain',
    description: 'Pedestrians forced to walk on busy carriage lane due to collapsed sidewalk slabs.',
    category_id: 'ROADS_FOOTPATH',
    category_name: 'Footpath Damage',
    department_id: 'd0000001-0000-0000-0000-000000000002',
    department_name: 'Roads & Infrastructure',
    status: 'created',
    priority: 'medium',
    address: 'Pondy Bazaar Pedestrian Plaza, T. Nagar',
    ward: 114,
    district: 'Chennai',
    latitude: 13.0412,
    longitude: 80.2371,
    created_at: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 19,
  },
  {
    id: 'dmt-tn-06',
    tracking_id: 'CC-TN-2026-104944',
    title: 'Deep pothole outside T. Nagar bus stand entry',
    description: 'MTC buses struggling to enter depot, tailback extending to Madley Subway.',
    category_id: 'ROADS_POTHOLE',
    category_name: 'Pothole',
    department_id: 'd0000001-0000-0000-0000-000000000002',
    department_name: 'Roads & Infrastructure',
    status: 'assigned',
    priority: 'high',
    address: 'T. Nagar Bus Terminus Entry, Venkatanarayana Rd',
    ward: 114,
    district: 'Chennai',
    latitude: 13.0398,
    longitude: 80.2338,
    created_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 64,
  },

  // ===========================================================================
  // CLUSTER 2: Chennai Velachery — Drinking Water & Pipeline Rupture (Ward 175)
  // Centroid: ~12.9915, 80.2185
  // ===========================================================================
  {
    id: 'dmt-vl-01',
    tracking_id: 'CC-TN-2026-218492',
    title: 'Drinking Water Main Pipeline Burst on Velachery Main Road',
    description: 'Major pipeline leak opposite Phoenix MarketCity. Clean drinking water flooding the road since 6 AM.',
    category_id: 'WATER_PIPE_LEAK',
    category_name: 'Pipe Leakage',
    department_id: 'd0000001-0000-0000-0000-000000000001',
    department_name: 'Water Supply',
    status: 'assigned',
    priority: 'urgent',
    address: 'Near Phoenix MarketCity, Velachery Main Road, Chennai',
    ward: 175,
    district: 'Chennai',
    latitude: 12.9915,
    longitude: 80.2185,
    created_at: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 87,
  },
  {
    id: 'dmt-vl-02',
    tracking_id: 'CC-TN-2026-218496',
    title: 'Severe pipeline gush near Velachery Lake junction',
    description: 'Drinking water spraying 2 meters high from underground valve crack.',
    category_id: 'WATER_PIPE_LEAK',
    category_name: 'Pipe Leakage',
    department_id: 'd0000001-0000-0000-0000-000000000001',
    department_name: 'Water Supply',
    status: 'in_progress',
    priority: 'urgent',
    address: 'Velachery Bypass Road, near Lake Bund, Chennai',
    ward: 175,
    district: 'Chennai',
    latitude: 12.9928,
    longitude: 80.2192,
    created_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 73,
  },
  {
    id: 'dmt-vl-03',
    tracking_id: 'CC-TN-2026-218501',
    title: 'Contaminated muddy water from municipal taps in Baby Nagar',
    description: 'Brown sewage-mixed water supplied through taps for the past 2 days.',
    category_id: 'WATER_CONTAMINATION',
    category_name: 'Water Contamination',
    department_id: 'd0000001-0000-0000-0000-000000000001',
    department_name: 'Water Supply',
    status: 'created',
    priority: 'urgent',
    address: 'Baby Nagar 2nd Main Road, Velachery',
    ward: 175,
    district: 'Chennai',
    latitude: 12.9902,
    longitude: 80.2178,
    created_at: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 95,
  },
  {
    id: 'dmt-vl-04',
    tracking_id: 'CC-TN-2026-218506',
    title: 'Zero water pressure in Gandhi Road households',
    description: 'No supply reaching overhead tanks due to mainline breach.',
    category_id: 'WATER_LOW_PRESSURE',
    category_name: 'Low Water Pressure',
    department_id: 'd0000001-0000-0000-0000-000000000001',
    department_name: 'Water Supply',
    status: 'assigned',
    priority: 'high',
    address: 'Gandhi Road, Velachery, Chennai',
    ward: 175,
    district: 'Chennai',
    latitude: 12.9898,
    longitude: 80.2199,
    created_at: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 44,
  },
  {
    id: 'dmt-vl-05',
    tracking_id: 'CC-TN-2026-218512',
    title: 'Secondary distribution pipe cracked on 100 Feet Road',
    description: 'Water pooling on carriageway creating slippery conditions.',
    category_id: 'WATER_PIPE_LEAK',
    category_name: 'Pipe Leakage',
    department_id: 'd0000001-0000-0000-0000-000000000001',
    department_name: 'Water Supply',
    status: 'created',
    priority: 'high',
    address: '100 Feet Bypass Road, Velachery, Chennai',
    ward: 175,
    district: 'Chennai',
    latitude: 12.9935,
    longitude: 80.2169,
    created_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 36,
  },

  // ===========================================================================
  // CLUSTER 3: Chennai Mylapore — Solid Waste & Sanitation (Ward 122)
  // Centroid: ~13.0336, 80.2697
  // ===========================================================================
  {
    id: 'dmt-my-01',
    tracking_id: 'CC-TN-2026-339104',
    title: 'Garbage Dump uncleared for 4 days near Mylapore Temple Tank',
    description: 'Heavy accumulation of mixed waste attracting stray animals near North Mada Street.',
    category_id: 'SANIT_NO_COLLECT',
    category_name: 'Garbage Not Collected',
    department_id: 'd0000001-0000-0000-0000-000000000003',
    department_name: 'Sanitation & Waste',
    status: 'resolved',
    priority: 'high',
    address: 'North Mada Street, Mylapore, Chennai',
    ward: 122,
    district: 'Chennai',
    latitude: 13.0336,
    longitude: 80.2697,
    created_at: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 53,
  },
  {
    id: 'dmt-my-02',
    tracking_id: 'CC-TN-2026-339109',
    title: 'Overflowing community compactor bin on South Mada St',
    description: 'Garbage spilling onto road, foul smell spreading into nearby flower shops.',
    category_id: 'SANIT_OVERFLOW',
    category_name: 'Overflowing Dustbin',
    department_id: 'd0000001-0000-0000-0000-000000000003',
    department_name: 'Sanitation & Waste',
    status: 'in_progress',
    priority: 'high',
    address: 'South Mada Street, Kapaleeshwarar Temple, Mylapore',
    ward: 122,
    district: 'Chennai',
    latitude: 13.0328,
    longitude: 80.2691,
    created_at: new Date(Date.now() - 8 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 47,
  },
  {
    id: 'dmt-my-03',
    tracking_id: 'CC-TN-2026-339115',
    title: 'Illegal commercial vegetable waste dumping on Luz Church Road',
    description: 'Trucks dumping rotten vegetables overnight behind shopping complex.',
    category_id: 'SANIT_ILLEGAL_DUMP',
    category_name: 'Illegal Dumping',
    department_id: 'd0000001-0000-0000-0000-000000000003',
    department_name: 'Sanitation & Waste',
    status: 'created',
    priority: 'high',
    address: 'Luz Church Road, near Luz Corner, Mylapore',
    ward: 122,
    district: 'Chennai',
    latitude: 13.0345,
    longitude: 80.2682,
    created_at: new Date(Date.now() - 6 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 61,
  },
  {
    id: 'dmt-my-04',
    tracking_id: 'CC-TN-2026-339120',
    title: 'Dead animal carcass unattended on East Mada Lane',
    description: 'Stray dog carcass decomposing in corner for over 24 hours.',
    category_id: 'SANIT_DEAD_ANIMAL',
    category_name: 'Dead Animal Removal',
    department_id: 'd0000001-0000-0000-0000-000000000003',
    department_name: 'Sanitation & Waste',
    status: 'resolved',
    priority: 'urgent',
    address: 'East Mada Street, Mylapore, Chennai',
    ward: 122,
    district: 'Chennai',
    latitude: 13.0331,
    longitude: 80.2711,
    created_at: new Date(Date.now() - 12 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 78,
  },
  {
    id: 'dmt-my-05',
    tracking_id: 'CC-TN-2026-339125',
    title: 'Unsegregated plastic accumulation near Kutchery Road intersection',
    description: 'Massive pile of single-use plastic blocking walkway.',
    category_id: 'SANIT_OVERFLOW',
    category_name: 'Overflowing Dustbin',
    department_id: 'd0000001-0000-0000-0000-000000000003',
    department_name: 'Sanitation & Waste',
    status: 'assigned',
    priority: 'medium',
    address: 'Kutchery Road, Mylapore, Chennai',
    ward: 122,
    district: 'Chennai',
    latitude: 13.0352,
    longitude: 80.2704,
    created_at: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 31,
  },

  // ===========================================================================
  // CLUSTER 4: Chennai Anna Nagar — Drainage & Sewage Overflow (Ward 102)
  // Centroid: ~13.0850, 80.2150
  // ===========================================================================
  {
    id: 'dmt-an-01',
    tracking_id: 'CC-TN-2026-440101',
    title: 'Sewage overflowing from manhole on 2nd Avenue',
    description: 'Black foul-smelling sewage bubbling out onto main commercial avenue.',
    category_id: 'DRAIN_SEWAGE',
    category_name: 'Sewage Overflow',
    department_id: 'd0000001-0000-0000-0000-000000000004',
    department_name: 'Drainage & Sewage',
    status: 'in_progress',
    priority: 'urgent',
    address: '2nd Avenue, near Roundtana, Anna Nagar',
    ward: 102,
    district: 'Chennai',
    latitude: 13.0852,
    longitude: 80.2148,
    created_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 89,
  },
  {
    id: 'dmt-an-02',
    tracking_id: 'CC-TN-2026-440105',
    title: 'Stormwater drain blocked by silt on 4th Main Road',
    description: 'Water unable to drain into canal, resulting in severe knee-deep stagnation.',
    category_id: 'DRAIN_BLOCKED',
    category_name: 'Blocked Drain',
    department_id: 'd0000001-0000-0000-0000-000000000004',
    department_name: 'Drainage & Sewage',
    status: 'assigned',
    priority: 'high',
    address: '4th Main Road, Anna Nagar West, Chennai',
    ward: 102,
    district: 'Chennai',
    latitude: 13.0861,
    longitude: 80.2139,
    created_at: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 62,
  },
  {
    id: 'dmt-an-03',
    tracking_id: 'CC-TN-2026-440110',
    title: 'Broken open manhole lid without warning barrier',
    description: 'Iron cover cracked in half. Danger of vehicles falling into deep drain.',
    category_id: 'DRAIN_MANHOLE',
    category_name: 'Manhole Issue',
    department_id: 'd0000001-0000-0000-0000-000000000004',
    department_name: 'Drainage & Sewage',
    status: 'created',
    priority: 'urgent',
    address: 'Near Tower Park Gate 2, 3rd Avenue, Anna Nagar',
    ward: 102,
    district: 'Chennai',
    latitude: 13.0845,
    longitude: 80.2162,
    created_at: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 104,
  },
  {
    id: 'dmt-an-04',
    tracking_id: 'CC-TN-2026-440116',
    title: 'Severe waterlogging at Shanthi Colony junction',
    description: 'Water standing for 3 days post rain, mosquito breeding ground.',
    category_id: 'DRAIN_WATERLOG',
    category_name: 'Waterlogging',
    department_id: 'd0000001-0000-0000-0000-000000000004',
    department_name: 'Drainage & Sewage',
    status: 'assigned',
    priority: 'high',
    address: 'Shanthi Colony 4th Avenue Junction, Anna Nagar',
    ward: 102,
    district: 'Chennai',
    latitude: 13.0839,
    longitude: 80.2155,
    created_at: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 45,
  },

  // ===========================================================================
  // CLUSTER 5: Coimbatore Gandhipuram — Electricity & Lighting (Ward 45)
  // Centroid: ~11.0168, 76.9658
  // ===========================================================================
  {
    id: 'dmt-cbe-01',
    tracking_id: 'CC-TN-2026-550101',
    title: 'Distribution Transformer sparking on Cross Cut Road',
    description: 'Loud buzzing and sparks observed from overhead commercial transformer.',
    category_id: 'ELEC_TRANSFORMER',
    category_name: 'Transformer Issue',
    department_id: 'd0000001-0000-0000-0000-000000000006',
    department_name: 'Electricity',
    status: 'assigned',
    priority: 'urgent',
    address: 'Cross Cut Road, Gandhipuram, Coimbatore',
    ward: 45,
    district: 'Coimbatore',
    latitude: 11.0168,
    longitude: 76.9658,
    created_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 76,
  },
  {
    id: 'dmt-cbe-02',
    tracking_id: 'CC-TN-2026-550105',
    title: 'Exposed live power wire hanging near bus shelter',
    description: 'Insulation peeled off cable hanging at 5 feet height near commuter queue.',
    category_id: 'ELEC_EXPOSED_WIRE',
    category_name: 'Exposed Wiring',
    department_id: 'd0000001-0000-0000-0000-000000000006',
    department_name: 'Electricity',
    status: 'in_progress',
    priority: 'urgent',
    address: 'Gandhipuram Central Bus Stand, Coimbatore',
    ward: 45,
    district: 'Coimbatore',
    latitude: 11.0175,
    longitude: 76.9664,
    created_at: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 112,
  },
  {
    id: 'dmt-cbe-03',
    tracking_id: 'CC-TN-2026-550110',
    title: 'Repeated phase outage on 7th Street Gandhipuram',
    description: 'Low voltage and single phase tripping every 20 minutes for 3 days.',
    category_id: 'ELEC_VOLTAGE',
    category_name: 'Voltage Fluctuation',
    department_id: 'd0000001-0000-0000-0000-000000000006',
    department_name: 'Electricity',
    status: 'created',
    priority: 'high',
    address: '7th Street, Gandhipuram, Coimbatore',
    ward: 45,
    district: 'Coimbatore',
    latitude: 11.0159,
    longitude: 76.9649,
    created_at: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 48,
  },
  {
    id: 'dmt-cbe-04',
    tracking_id: 'CC-TN-2026-550115',
    title: 'Row of 8 LED streetlights non-functional on 100 Feet Rd',
    description: 'Complete darkness along major commercial stretch after 7 PM.',
    category_id: 'LIGHT_NOT_WORKING',
    category_name: 'Light Not Working',
    department_id: 'd0000001-0000-0000-0000-000000000005',
    department_name: 'Street Lighting',
    status: 'assigned',
    priority: 'medium',
    address: '100 Feet Road, Gandhipuram, Coimbatore',
    ward: 45,
    district: 'Coimbatore',
    latitude: 11.0181,
    longitude: 76.9672,
    created_at: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 37,
  },

  // ===========================================================================
  // CLUSTER 6: Madurai Simmakkal — Drainage & Waterlogging (Ward 22)
  // Centroid: ~9.9252, 78.1198
  // ===========================================================================
  {
    id: 'dmt-mdu-01',
    tracking_id: 'CC-TN-2026-660101',
    title: 'Major sewage block near Simmakkal Roundabout',
    description: 'Underground conduit blocked by construction debris, flooding North Veli Street.',
    category_id: 'DRAIN_BLOCKED',
    category_name: 'Blocked Drain',
    department_id: 'd0000001-0000-0000-0000-000000000004',
    department_name: 'Drainage & Sewage',
    status: 'in_progress',
    priority: 'urgent',
    address: 'Simmakkal Roundabout, North Veli St, Madurai',
    ward: 22,
    district: 'Madurai',
    latitude: 9.9252,
    longitude: 78.1198,
    created_at: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 82,
  },
  {
    id: 'dmt-mdu-02',
    tracking_id: 'CC-TN-2026-660105',
    title: 'Foul water stagnant near Vaigai river approach lane',
    description: 'Drain water backing up into residential basements near bridge ramp.',
    category_id: 'DRAIN_WATERLOG',
    category_name: 'Waterlogging',
    department_id: 'd0000001-0000-0000-0000-000000000004',
    department_name: 'Drainage & Sewage',
    status: 'created',
    priority: 'high',
    address: 'Yanaikkal Road, Simmakkal, Madurai',
    ward: 22,
    district: 'Madurai',
    latitude: 9.9261,
    longitude: 78.1205,
    created_at: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 67,
  },
  {
    id: 'dmt-mdu-03',
    tracking_id: 'CC-TN-2026-660110',
    title: 'Sewage canal overflowing into fruit market premises',
    description: 'Extreme health hazard with waste entering retail stall floorings.',
    category_id: 'DRAIN_SEWAGE',
    category_name: 'Sewage Overflow',
    department_id: 'd0000001-0000-0000-0000-000000000004',
    department_name: 'Drainage & Sewage',
    status: 'assigned',
    priority: 'urgent',
    address: 'Simmakkal Central Fruit Market, Madurai',
    ward: 22,
    district: 'Madurai',
    latitude: 9.9245,
    longitude: 78.1191,
    created_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 93,
  },

  // ===========================================================================
  // CLUSTER 7: Salem Gugai — Road Infrastructure (Ward 31)
  // Centroid: ~11.6420, 78.1580
  // ===========================================================================
  {
    id: 'dmt-slm-01',
    tracking_id: 'CC-TN-2026-770101',
    title: 'Cracked bitumen road on Gugai Main Bazaar',
    description: 'Heavy weaving trucks have crushed the shoulder of the road.',
    category_id: 'ROADS_DAMAGE',
    category_name: 'Road Damage',
    department_id: 'd0000001-0000-0000-0000-000000000002',
    department_name: 'Roads & Infrastructure',
    status: 'created',
    priority: 'high',
    address: 'Gugai Main Road, Salem',
    ward: 31,
    district: 'Salem',
    latitude: 11.6420,
    longitude: 78.1580,
    created_at: new Date(Date.now() - 6 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 34,
  },
  {
    id: 'dmt-slm-02',
    tracking_id: 'CC-TN-2026-770105',
    title: 'Deep pothole outside Gugai Mariamman Temple',
    description: 'Devotees and vehicles facing severe issues on festival path.',
    category_id: 'ROADS_POTHOLE',
    category_name: 'Pothole',
    department_id: 'd0000001-0000-0000-0000-000000000002',
    department_name: 'Roads & Infrastructure',
    status: 'assigned',
    priority: 'high',
    address: 'Trichy Main Road, Gugai, Salem',
    ward: 31,
    district: 'Salem',
    latitude: 11.6429,
    longitude: 78.1588,
    created_at: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 41,
  },
  {
    id: 'dmt-slm-03',
    tracking_id: 'CC-TN-2026-770109',
    title: 'Culvert slab fractured on Line Medu crossing',
    description: 'Heavy goods vehicle cracked the drainage culvert causing dip in road.',
    category_id: 'ROADS_BRIDGE',
    category_name: 'Bridge Issue',
    department_id: 'd0000001-0000-0000-0000-000000000002',
    department_name: 'Roads & Infrastructure',
    status: 'in_progress',
    priority: 'urgent',
    address: 'Line Medu, Gugai, Salem',
    ward: 31,
    district: 'Salem',
    latitude: 11.6412,
    longitude: 78.1572,
    created_at: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 55,
  },

  // ===========================================================================
  // CLUSTER 8: Tiruchirappalli Thillai Nagar — Water Supply (Ward 54)
  // Centroid: ~10.8285, 78.6865
  // ===========================================================================
  {
    id: 'dmt-try-01',
    tracking_id: 'CC-TN-2026-880101',
    title: 'Main water distribution pipe leak on 11th Cross',
    description: 'Drinking water leaking into roadside storm canal continuously.',
    category_id: 'WATER_PIPE_LEAK',
    category_name: 'Pipe Leakage',
    department_id: 'd0000001-0000-0000-0000-000000000001',
    department_name: 'Water Supply',
    status: 'assigned',
    priority: 'high',
    address: '11th Cross, Thillai Nagar, Tiruchirappalli',
    ward: 54,
    district: 'Tiruchirappalli',
    latitude: 10.8285,
    longitude: 78.6865,
    created_at: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 49,
  },
  {
    id: 'dmt-try-02',
    tracking_id: 'CC-TN-2026-880105',
    title: 'Low pressure water supply in Shastri Road apartments',
    description: 'Only 15 minutes of trickle water provided in morning supply hour.',
    category_id: 'WATER_LOW_PRESSURE',
    category_name: 'Low Water Pressure',
    department_id: 'd0000001-0000-0000-0000-000000000001',
    department_name: 'Water Supply',
    status: 'created',
    priority: 'medium',
    address: 'Shastri Road, Thillai Nagar, Tiruchirappalli',
    ward: 54,
    district: 'Tiruchirappalli',
    latitude: 10.8292,
    longitude: 78.6872,
    created_at: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 28,
  },
  {
    id: 'dmt-try-03',
    tracking_id: 'CC-TN-2026-880109',
    title: 'Sewage seepage into Cauvery water pipeline on Salai Road',
    description: 'Tap water smells of sewage, urgent inspection requested.',
    category_id: 'WATER_CONTAMINATION',
    category_name: 'Water Contamination',
    department_id: 'd0000001-0000-0000-0000-000000000001',
    department_name: 'Water Supply',
    status: 'in_progress',
    priority: 'urgent',
    address: 'Salai Road, Thillai Nagar East, Tiruchirappalli',
    ward: 54,
    district: 'Tiruchirappalli',
    latitude: 10.8278,
    longitude: 78.6858,
    created_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 91,
  },

  // ===========================================================================
  // NOISE & OUTLIER POINTS (Dispersed across Rural & Semi-Urban TN)
  // Demonstrates DBSCAN Noise point identification (cluster_id = -1)
  // ===========================================================================
  {
    id: 'dmt-noise-01',
    tracking_id: 'CC-TN-2026-990001',
    title: 'Isolated street lamp blink on Nilgiris Tea Estate hairpin bend',
    description: 'Solar light blinking intermittently on mountain curve.',
    category_id: 'LIGHT_NOT_WORKING',
    category_name: 'Light Not Working',
    department_id: 'd0000001-0000-0000-0000-000000000005',
    department_name: 'Street Lighting',
    status: 'created',
    priority: 'low',
    address: 'Hairpin Bend 8, Coonoor Ghat Road, Nilgiris',
    ward: 4,
    district: 'Nilgiris',
    latitude: 11.3530,
    longitude: 76.7959,
    created_at: new Date(Date.now() - 15 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 5,
  },
  {
    id: 'dmt-noise-02',
    tracking_id: 'CC-TN-2026-990002',
    title: 'Fallen tree branch on remote Dharmapuri village road',
    description: 'Branch partially resting on mud road shoulder.',
    category_id: 'ROADS_DAMAGE',
    category_name: 'Road Damage',
    department_id: 'd0000001-0000-0000-0000-000000000002',
    department_name: 'Roads & Infrastructure',
    status: 'resolved',
    priority: 'low',
    address: 'Pennagaram Rural Road, Dharmapuri',
    ward: 2,
    district: 'Dharmapuri',
    latitude: 12.1211,
    longitude: 77.8865,
    created_at: new Date(Date.now() - 20 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 3,
  },
  {
    id: 'dmt-noise-03',
    tracking_id: 'CC-TN-2026-990003',
    title: 'Single dustbin damage in Sivaganga village market',
    description: 'Plastic wheel broken on single bin.',
    category_id: 'SANIT_OVERFLOW',
    category_name: 'Overflowing Dustbin',
    department_id: 'd0000001-0000-0000-0000-000000000003',
    department_name: 'Sanitation & Waste',
    status: 'created',
    priority: 'low',
    address: 'Ilayangudi Road, Sivaganga',
    ward: 7,
    district: 'Sivaganga',
    latitude: 9.8433,
    longitude: 78.4809,
    created_at: new Date(Date.now() - 18 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 2,
  },
  {
    id: 'dmt-noise-04',
    tracking_id: 'CC-TN-2026-990004',
    title: 'Small trench dug for tube well in Ramanathapuram coast',
    description: 'Sand trench needs leveling.',
    category_id: 'ROADS_DAMAGE',
    category_name: 'Road Damage',
    department_id: 'd0000001-0000-0000-0000-000000000002',
    department_name: 'Roads & Infrastructure',
    status: 'created',
    priority: 'low',
    address: 'Mandapam coastal road, Ramanathapuram',
    ward: 1,
    district: 'Ramanathapuram',
    latitude: 9.2783,
    longitude: 79.1245,
    created_at: new Date(Date.now() - 25 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 4,
  },
  {
    id: 'dmt-noise-05',
    tracking_id: 'CC-TN-2026-990005',
    title: 'Cattle grazing on canal bund in Theni rural boundary',
    description: 'Minor bund erosion caused by cattle movement.',
    category_id: 'GEN_NUISANCE',
    category_name: 'Public Nuisance',
    department_id: 'd0000001-0000-0000-0000-000000000008',
    department_name: 'General Administration',
    status: 'closed',
    priority: 'low',
    address: 'Bodi Highway Canal, Theni',
    ward: 3,
    district: 'Theni',
    latitude: 10.0104,
    longitude: 77.4768,
    created_at: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
    upvotes_count: 1,
  },
];
