// =============================================================================
// CivicConnect TN — Scalable CSV Export Serializer (RFC 4180 + UTF-8 BOM)
// =============================================================================

import { ExportResult, ReportDataPayload } from '../types';

/**
 * Escapes a field according to RFC 4180 CSV specifications.
 */
function escapeCsvField(val: any): string {
  if (val === null || val === undefined) return '';
  const str = String(val);
  if (str.includes(',') || str.includes('"') || str.includes('\n') || str.includes('\r')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

/**
 * Serializes a ReportDataPayload into a standardized CSV document with metadata comments.
 */
export function exportReportToCsv(payload: ReportDataPayload): ExportResult {
  const lines: string[] = [];

  // 1. UTF-8 Byte Order Mark (BOM) for seamless Excel & spreadsheet rendering
  const bom = '\uFEFF';

  // 2. Metadata Commentary Block
  lines.push(`# =============================================================================`);
  lines.push(`# CIVICCONNECT TN — ${payload.metadata.organization.toUpperCase()}`);
  lines.push(`# REPORT: ${payload.metadata.title.toUpperCase()}`);
  lines.push(`# SUBTITLE: ${payload.metadata.subtitle}`);
  lines.push(`# GENERATED AT: ${payload.metadata.generatedAt}`);
  lines.push(`# GENERATED BY: ${payload.metadata.generatedBy}`);
  lines.push(`# SCOPE: Department: ${payload.metadata.departmentScope} | District: ${payload.metadata.districtScope} | Date: ${payload.metadata.dateScope}`);
  lines.push(`# TOTAL RECORDS: ${payload.metadata.totalRecords}`);
  lines.push(`# =============================================================================`);
  lines.push('');

  // 3. Executive KPI Summary Block
  lines.push(`# --- EXECUTIVE KPI SUMMARY ---`);
  payload.kpis.forEach((kpi) => {
    lines.push(`# ${kpi.label}: ${kpi.value} ${kpi.unit || ''} (${kpi.subtext || ''})`);
  });
  lines.push('');

  // 4. Summary Sections (if any)
  if (payload.summarySections && payload.summarySections.length > 0) {
    payload.summarySections.forEach((sec) => {
      lines.push(`# --- ${sec.title.toUpperCase()} ---`);
      sec.items.forEach((item) => {
        lines.push(`# ${item.label}: ${item.value}`);
      });
      lines.push('');
    });
  }

  // 5. Column Headers Row
  const headerRow = payload.columns.map((c) => escapeCsvField(c.label)).join(',');
  lines.push(headerRow);

  // 6. Data Rows
  payload.rows.forEach((row) => {
    const rowLine = payload.columns.map((col) => escapeCsvField(row[col.key])).join(',');
    lines.push(rowLine);
  });

  const csvContent = bom + lines.join('\r\n');
  const buffer = Buffer.from(csvContent, 'utf-8');

  const filename = `${payload.metadata.reportType}_${new Date().toISOString().slice(0, 10)}.csv`;

  return {
    buffer,
    mimeType: 'text/csv; charset=utf-8',
    filename,
    format: 'csv',
    sizeBytes: buffer.length,
  };
}
