// =============================================================================
// CivicConnect TN — Professional Excel (.xlsx) Report Exporter
// =============================================================================

import ExcelJS from 'exceljs';
import { ExportResult, ReportDataPayload } from '../types';

export async function exportReportToExcel(payload: ReportDataPayload): Promise<ExportResult> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'CivicConnect TN — Government of Tamil Nadu';
  workbook.lastModifiedBy = payload.metadata.generatedBy;
  workbook.created = new Date();
  workbook.modified = new Date();

  // ---------------------------------------------------------------------------
  // TAB 1: EXECUTIVE OVERVIEW
  // ---------------------------------------------------------------------------
  const overviewSheet = workbook.addWorksheet('Executive Overview', {
    views: [{ showGridLines: true }],
  });

  // Top Title Banner
  overviewSheet.mergeCells('A1:G1');
  const titleCell = overviewSheet.getCell('A1');
  titleCell.value = 'GOVERNMENT OF TAMIL NADU — CIVICCONNECT TN';
  titleCell.font = { name: 'Calibri', size: 14, bold: true, color: { argb: 'FFFFFFFF' } };
  titleCell.fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FF0F5132' }, // Tamil Nadu Official Emerald Green
  };
  titleCell.alignment = { horizontal: 'center', vertical: 'middle' };
  overviewSheet.getRow(1).height = 30;

  // Report Subtitle
  overviewSheet.mergeCells('A2:G2');
  const subCell = overviewSheet.getCell('A2');
  subCell.value = payload.metadata.title.toUpperCase();
  subCell.font = { name: 'Calibri', size: 12, bold: true, color: { argb: 'FF1B4332' } };
  subCell.alignment = { horizontal: 'center', vertical: 'middle' };
  overviewSheet.getRow(2).height = 24;

  // Metadata Grid
  overviewSheet.getCell('A4').value = 'Report Description:';
  overviewSheet.getCell('A4').font = { bold: true };
  overviewSheet.mergeCells('B4:G4');
  overviewSheet.getCell('B4').value = payload.metadata.description;

  overviewSheet.getCell('A5').value = 'Generated At:';
  overviewSheet.getCell('A5').font = { bold: true };
  overviewSheet.getCell('B5').value = payload.metadata.generatedAt;

  overviewSheet.getCell('D5').value = 'Generated By:';
  overviewSheet.getCell('D5').font = { bold: true };
  overviewSheet.getCell('E5').value = payload.metadata.generatedBy;

  overviewSheet.getCell('A6').value = 'Department Scope:';
  overviewSheet.getCell('A6').font = { bold: true };
  overviewSheet.getCell('B6').value = payload.metadata.departmentScope;

  overviewSheet.getCell('D6').value = 'District Scope:';
  overviewSheet.getCell('D6').font = { bold: true };
  overviewSheet.getCell('E6').value = payload.metadata.districtScope;

  overviewSheet.getCell('A7').value = 'Date Scope:';
  overviewSheet.getCell('A7').font = { bold: true };
  overviewSheet.getCell('B7').value = payload.metadata.dateScope;

  overviewSheet.getCell('D7').value = 'Total Records:';
  overviewSheet.getCell('D7').font = { bold: true };
  overviewSheet.getCell('E7').value = payload.metadata.totalRecords;

  // KPI Table Header
  overviewSheet.mergeCells('A9:G9');
  const kpiHeader = overviewSheet.getCell('A9');
  kpiHeader.value = 'KEY PERFORMANCE INDICATORS (KPI)';
  kpiHeader.font = { bold: true, color: { argb: 'FFFFFFFF' } };
  kpiHeader.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF198754' } };
  overviewSheet.getRow(9).height = 22;

  overviewSheet.getCell('A10').value = 'Metric Label';
  overviewSheet.getCell('B10').value = 'Value';
  overviewSheet.getCell('C10').value = 'Unit / Subtext';
  overviewSheet.getCell('D10').value = 'Status Tone';
  ['A10', 'B10', 'C10', 'D10'].forEach((cellId) => {
    const c = overviewSheet.getCell(cellId);
    c.font = { bold: true };
    c.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE9ECEF' } };
  });

  let kpiRowIndex = 11;
  payload.kpis.forEach((kpi) => {
    overviewSheet.getCell(`A${kpiRowIndex}`).value = kpi.label;
    overviewSheet.getCell(`B${kpiRowIndex}`).value = kpi.value;
    overviewSheet.getCell(`C${kpiRowIndex}`).value = `${kpi.unit || ''} ${kpi.subtext ? `(${kpi.subtext})` : ''}`;
    overviewSheet.getCell(`D${kpiRowIndex}`).value = kpi.tone.toUpperCase();
    kpiRowIndex++;
  });

  // Summary Sections (if any)
  if (payload.summarySections && payload.summarySections.length > 0) {
    let secRowIndex = kpiRowIndex + 2;
    payload.summarySections.forEach((sec) => {
      overviewSheet.mergeCells(`A${secRowIndex}:G${secRowIndex}`);
      const secHeader = overviewSheet.getCell(`A${secRowIndex}`);
      secHeader.value = sec.title.toUpperCase();
      secHeader.font = { bold: true, color: { argb: 'FFFFFFFF' } };
      secHeader.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF212529' } };
      secRowIndex++;

      sec.items.forEach((item) => {
        overviewSheet.getCell(`A${secRowIndex}`).value = item.label;
        overviewSheet.getCell(`A${secRowIndex}`).font = { bold: true };
        overviewSheet.mergeCells(`B${secRowIndex}:G${secRowIndex}`);
        overviewSheet.getCell(`B${secRowIndex}`).value = item.value;
        secRowIndex++;
      });
      secRowIndex++;
    });
  }

  // Adjust column widths for Overview Sheet
  overviewSheet.columns = [
    { width: 26 },
    { width: 30 },
    { width: 28 },
    { width: 20 },
    { width: 26 },
    { width: 20 },
    { width: 20 },
  ];

  // ---------------------------------------------------------------------------
  // TAB 2: DATA REGISTER (DETAILED ROWS)
  // ---------------------------------------------------------------------------
  const dataSheet = workbook.addWorksheet('Data Register', {
    views: [{ state: 'frozen', ySplit: 1, showGridLines: true }],
  });

  // Header Row
  const headerRow = dataSheet.addRow(payload.columns.map((c) => c.label));
  headerRow.height = 26;
  headerRow.eachCell((cell) => {
    cell.font = { name: 'Calibri', size: 11, bold: true, color: { argb: 'FFFFFFFF' } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0F5132' } };
    cell.alignment = { horizontal: 'center', vertical: 'middle' };
    cell.border = {
      top: { style: 'thin' },
      left: { style: 'thin' },
      bottom: { style: 'medium' },
      right: { style: 'thin' },
    };
  });

  // Data Rows
  payload.rows.forEach((rowObj, index) => {
    const rowValues = payload.columns.map((col) => rowObj[col.key] ?? '');
    const row = dataSheet.addRow(rowValues);
    row.height = 20;

    const isZebra = index % 2 === 1;
    row.eachCell((cell, colNum) => {
      const colDef = payload.columns[colNum - 1];

      cell.font = { name: 'Calibri', size: 10 };
      cell.alignment = {
        horizontal: colDef?.align || 'left',
        vertical: 'middle',
      };

      if (isZebra) {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF8F9FA' } };
      }

      // Priority & Status conditional highlighting
      const valStr = String(cell.value || '').toUpperCase();
      if (valStr === 'URGENT' || valStr === 'BREACHED' || valStr === 'CRITICAL') {
        cell.font = { bold: true, color: { argb: 'FFDC3545' } };
      } else if (valStr === 'HIGH' || valStr === '75% WARNING' || valStr === 'L2 DEPT HEAD') {
        cell.font = { bold: true, color: { argb: 'FFD97706' } };
      } else if (valStr === 'RESOLVED' || valStr === 'VERIFIED' || valStr === 'MET ON TIME' || valStr === 'HIGH DENSITY') {
        cell.font = { bold: true, color: { argb: 'FF198754' } };
      }

      cell.border = {
        top: { style: 'thin', color: { argb: 'FFE5E7EB' } },
        left: { style: 'thin', color: { argb: 'FFE5E7EB' } },
        bottom: { style: 'thin', color: { argb: 'FFE5E7EB' } },
        right: { style: 'thin', color: { argb: 'FFE5E7EB' } },
      };
    });
  });

  // Auto-fit Column Widths for Data Sheet
  dataSheet.columns = payload.columns.map((col) => {
    const minW = Math.max(12, col.label.length + 4);
    const configuredW = col.width ? Math.round(col.width * 1.5) : minW;
    return { width: Math.max(minW, Math.min(configuredW, 45)) };
  });

  // Auto-filter
  dataSheet.autoFilter = {
    from: { row: 1, column: 1 },
    to: { row: 1, column: payload.columns.length },
  };

  const rawBuffer = await workbook.xlsx.writeBuffer();
  const buffer = Buffer.from(rawBuffer);
  const filename = `${payload.metadata.reportType}_${new Date().toISOString().slice(0, 10)}.xlsx`;

  return {
    buffer,
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    filename,
    format: 'excel',
    sizeBytes: buffer.length,
  };
}
